### ISSUE TITLE
replace *fiber.App with fiber.Router Interface

### ISSUE THREAD

**Issue by hotrungnhan** [create-go-app/fiber-go-template#77]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the repository's issues section similar bug.
- [x] I understand, this is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/40029631/132944552-b3ab3d25-49e1-4d07-817f-85be39b1cf9f.png)
it was like you have default paramente is *fiber.App which is not flexible when we need to change or group some api.
i suggest that you can replace with fiber.Router
![image](https://user-images.githubusercontent.com/40029631/132944600-1a9db9fd-803c-4eae-803c-19fa5389a11a.png)
then we can easilier to group it in main file.

**Comment by koddr** [comment]
Hi,

I don't know why this option seems better to you, but I'll try to explain by example why I chose this way of organizing routes in the application. In the world of Go, it is a good thing to make _fallback_ versions for REST API methods that are _outdated_ but still in demand by users. 

For this reason, to easily support two different versions of the API in one Fiber application, I will simply create another route file in which I set the next version of the API, like this:

```go
// ./pkg/routes/public_routes_v2.go

// PublicRoutesV2 func for describe group of public routes for API v2.
func PublicRoutesV2(a *fiber.App) {
	// Create routes group.
	route := a.Group("/api/v2")

	// Routes for GET method:
	route.Get("/books", controllers.GetBooksV2) // <-- get list of all books for API v2

        // ...
}
```

Note that all controllers for the new version of the API are also marked with the new names (with the ending `V2` to make it easier to identify them).

And next, I will add this new routes group to the `main.go`, like this:

```go
// ./main.go

// ...
func main() {
	// ...

	// Routes.
	// ...
	routes.PublicRoutesV2(app)  // <-- Register a public routes with API v2 for app.
	// ...
}
```

As you can see, this way of organizing code in Fiber application allows you to keep a fallback version (for v1 users) and add new routes to make changes to the v2 API. And most _importantly_, this way is absolutely transparent for understanding and subsequent writing of unit tests because everything lies in its place: the description of routes and their challenge. 😉 

> If you are more convenient to use the option you gave in the example, then you are absolutely free to use it in your application! But I hope I've explained to you my point of view on this application template and the decisions made in it.

**Comment by hotrungnhan** [comment]
Sincerely thanks for explain me how this template work , you've show me a great point of view.
